name: postgres

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install postgresql-client

      - name: Load schema
        run: |
          export PGPASSWORD=postgres
          psql -h localhost -U postgres -d postgres -f ./postgres.sql
          psql -h localhost -U postgres -d postgres -f ./postgres_schema.sql
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test-postgres
        timeout-minutes: 5
